source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MomentsPicker_Example', :exclusive => true do
  pod "MomentsPicker", :path => "../"
end

target 'MomentsPicker_Tests', :exclusive => true do
  pod "MomentsPicker", :path => "../"
end
