//
//  Constants.swift
//  Pods
//
//  Created by Wang Zhenghong on 2015/11/25.
//
//

import Foundation

enum PHOTO_DEFAULT_RATIO_H_2_W: CGFloat {
    case IPHONE_6 = 1.33
}

let NUMBER_OF_COLUMN_IN_SUB_COLLECTION: Int = 4
let LINE_HEIGHT_IN_SUB_COLLECTION: CGFloat = 1.0

let MOMENTS_LIST_CELL_TITLE_HEIGHT: Int = 24
let MOMENTS_LIST_CELL_SUBTITLE_HEIGHT: Int = 18
let MOMENTS_LIST_CELL_TITLE_AREA_HEIGHT: Int = MOMENTS_LIST_CELL_SUBTITLE_HEIGHT + MOMENTS_LIST_CELL_TITLE_HEIGHT